package poster

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"strconv"
	"strings"
	"time"

	"log/slog"

	"migadu/mizu/pkg/metrics"
)

// statusCodeBucket maps an HTTP status code to a bucket label (e.g. "2xx", "4xx", "5xx")
// to avoid unbounded label cardinality in Prometheus metrics.
func statusCodeBucket(code int) string {
	switch {
	case code >= 200 && code < 300:
		return "2xx"
	case code >= 300 && code < 400:
		return "3xx"
	case code >= 400 && code < 500:
		return "4xx"
	case code >= 500 && code < 600:
		return "5xx"
	default:
		return "other"
	}
}

// NewHTTPClient creates a new HTTP client with the specified timeout and connection pool settings.
// The timeout controls the maximum time for the entire request/response cycle.
// maxIdleConnsPerHost controls how many idle connections to keep per backend host (0 = use default 100).
// maxConnsPerHost limits total connections per host (0 = unlimited).
// idleConnTimeout controls how long idle connections stay in the pool (0 = use default 90s).
// These settings are critical for high-throughput relay scenarios — Go's default of 2 idle
// connections per host is insufficient when posting many emails to a single backend.
func NewHTTPClient(timeout time.Duration, maxIdleConnsPerHost, maxConnsPerHost int, idleConnTimeout time.Duration) *http.Client {
	// Apply sensible defaults if not configured
	if maxIdleConnsPerHost <= 0 {
		maxIdleConnsPerHost = 100
	}
	if idleConnTimeout <= 0 {
		idleConnTimeout = 90 * time.Second
	}

	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.MaxIdleConns = maxIdleConnsPerHost * 2 // Total idle connections across all hosts
	transport.MaxIdleConnsPerHost = maxIdleConnsPerHost
	transport.MaxConnsPerHost = maxConnsPerHost // 0 = unlimited
	transport.IdleConnTimeout = idleConnTimeout

	return &http.Client{
		Timeout:   timeout,
		Transport: transport,
		// A delivery endpoint has no legitimate redirect use. Stop at the first
		// response instead of following 3xx, which could re-route the message
		// body (Go only strips the Authorization header on cross-host redirects,
		// so the message itself would still be forwarded wherever pointed).
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
}

// SpamVerdict is the external spam checker's (rspamd) result for a message.
type SpamVerdict struct {
	Score  float64 // Numeric spam score
	Action string  // Rspamd action, e.g. "no action", "add header", "greylist", "reject"
}

// Delivery describes one message delivery to the backend: the message itself,
// where to send it, and the per-message metadata forwarded as HTTP request
// headers. All metadata travels in the HTTP envelope only; nothing here is
// written into the RFC 822 body, so recipients never see it.
type Delivery struct {
	RawEmail         string // Full RFC 822 message, sent verbatim as the request body
	URL              string // Backend endpoint
	AuthToken        string // Bearer token; empty means no Authorization header (URL-based auth)
	MaxRetryAttempts int    // Total attempts including the first; values < 1 mean 1

	MailFrom          string // Envelope MAIL FROM (X-Mail-From); empty for the null sender
	MailTo            string // Envelope RCPT TO for this delivery (X-Mail-To)
	TraceID           string // Session trace ID (X-Trace-ID)
	AuthenticatedUser string // SMTP AUTH username (X-Auth-User); empty when unauthenticated

	Origin   string // Server type that accepted the message: "relay" or "submission" (X-Mail-Origin)
	ClientIP string // Connecting client IP without port (X-Client-IP)

	IsJunk     bool         // Message classified as junk by any check (X-Junk: yes)
	JunkAction string       // Junk apply_action mizu applied to the body ("header", "subject", "warn"); empty when not junk (X-Junk-Action)
	Spam       *SpamVerdict // Rspamd result (X-Spam-Score, X-Spam-Action); nil when spam checking did not run
}

// applyHeaders sets the HTTP request headers that describe this delivery.
// Optional values are omitted when empty so the backend can distinguish
// "not applicable" from an empty string.
func (d Delivery) applyHeaders(req *http.Request) {
	req.Header.Set("Content-Type", "message/rfc822") // RFC 2822 compliant email format

	// Only set the token if provided (custom endpoints may use URL-based auth)
	if d.AuthToken != "" {
		req.Header.Set("Authorization", "Bearer "+d.AuthToken)
	}

	// Envelope addresses
	if d.MailFrom != "" {
		req.Header.Set("X-Mail-From", d.MailFrom)
	}
	if d.MailTo != "" {
		req.Header.Set("X-Mail-To", d.MailTo)
	}

	// Distributed tracing and log correlation
	if d.TraceID != "" {
		req.Header.Set("X-Trace-ID", d.TraceID)
	}

	// Authenticated submission
	if d.AuthenticatedUser != "" {
		req.Header.Set("X-Auth-User", d.AuthenticatedUser)
	}

	// Origin and connecting client. Both are generated by mizu (config value and
	// the parsed socket address), never copied from client-supplied text, so no
	// value here can carry bytes that would make the transport reject the request.
	if d.Origin != "" {
		req.Header.Set("X-Mail-Origin", d.Origin)
	}
	if d.ClientIP != "" {
		req.Header.Set("X-Client-IP", d.ClientIP)
	}

	// Spam classification
	if d.IsJunk {
		req.Header.Set("X-Junk", "yes")
	}
	if d.JunkAction != "" {
		req.Header.Set("X-Junk-Action", d.JunkAction)
	}
	if d.Spam != nil {
		req.Header.Set("X-Spam-Score", strconv.FormatFloat(d.Spam.Score, 'f', 2, 64))
		if d.Spam.Action != "" {
			req.Header.Set("X-Spam-Action", d.Spam.Action)
		}
	}
}

// PostEmailToDestinationWithContext sends the raw email content to the destination with retry logic and context support.
// It implements exponential backoff between retries and respects context cancellation.
// The message and its metadata are described by d; see Delivery for the HTTP headers each field maps to.
// The circuitBreaker parameter is optional - if provided, each retry attempt will be protected by the circuit breaker.
// The httpClient parameter specifies the HTTP client to use for requests (with configured timeout).
func PostEmailToDestinationWithContext(ctx context.Context, d Delivery, circuitBreaker *CircuitBreaker, httpClient *http.Client, logger *slog.Logger, m *metrics.Metrics) error {
	return postEmailWithRetries(ctx, d, circuitBreaker, httpClient, logger, m)
}

// postEmailWithRetries contains the actual retry logic with circuit breaker protection per attempt
func postEmailWithRetries(ctx context.Context, d Delivery, circuitBreaker *CircuitBreaker, httpClient *http.Client, logger *slog.Logger, m *metrics.Metrics) error {
	var lastErr error

	// Ensure at least one attempt even if configured incorrectly
	maxRetryAttempts := d.MaxRetryAttempts
	if maxRetryAttempts < 1 {
		maxRetryAttempts = 1
	}

	// Retry loop with exponential backoff
	for attempt := 0; attempt < maxRetryAttempts; attempt++ {
		// Check if context is cancelled
		select {
		case <-ctx.Done():
			return fmt.Errorf("context cancelled: %w", ctx.Err())
		default:
		}

		// Implement exponential backoff between retries to avoid overwhelming the destination
		// Backoff sequence: 0s (first attempt), 1s, 2s, 4s, 8s, etc.
		if attempt > 0 {
			backoff := time.Duration(1<<(attempt-1)) * time.Second
			logger.Info(fmt.Sprintf("Retrying HTTP post to URL (attempt %d/%d) after %v delay", attempt+1, maxRetryAttempts, backoff))

			// Sleep with context awareness - allows early cancellation
			select {
			case <-time.After(backoff):
				// Continue after backoff
			case <-ctx.Done():
				return fmt.Errorf("context cancelled during backoff: %w", ctx.Err())
			}
		}

		// Execute this attempt with circuit breaker protection
		var err error
		if circuitBreaker != nil {
			// Circuit breaker protects each individual attempt
			err = circuitBreaker.Call(func() error {
				return postEmailAttemptWithContext(ctx, d, httpClient, logger, m)
			})
		} else {
			// No circuit breaker - call directly
			err = postEmailAttemptWithContext(ctx, d, httpClient, logger, m)
		}

		if err == nil {
			// Success
			return nil
		}

		lastErr = err

		// Determine if the error warrants a retry
		// Non-retryable errors (like 4xx HTTP codes) fail immediately
		if !IsRetryableError(err) {
			logger.Warn(fmt.Sprintf("Non-retryable error posting to URL: %v", err))
			return err
		}

		if attempt < maxRetryAttempts-1 {
			logger.Warn(fmt.Sprintf("Retryable error posting to URL (attempt %d/%d): %v", attempt+1, maxRetryAttempts, err))
		}
	}

	// All retries exhausted
	logger.Error(fmt.Sprintf("All retry attempts exhausted (%d/%d) posting to URL: %v", maxRetryAttempts, maxRetryAttempts, lastErr))
	return fmt.Errorf("failed after %d attempts: %w", maxRetryAttempts, lastErr)
}

// postEmailAttemptWithContext performs a single attempt to post the email with context support.
// It sends the raw email as message/rfc822 content type with the delivery metadata as request headers.
func postEmailAttemptWithContext(ctx context.Context, d Delivery, httpClient *http.Client, logger *slog.Logger, m *metrics.Metrics) error {
	if httpClient == nil {
		return fmt.Errorf("httpClient cannot be nil")
	}

	req, err := http.NewRequestWithContext(ctx, "POST", d.URL, strings.NewReader(d.RawEmail))
	if err != nil {
		return fmt.Errorf("failed to create HTTP request: %w", err)
	}
	d.applyHeaders(req)

	start := time.Now()
	resp, err := httpClient.Do(req)
	duration := time.Since(start).Seconds()
	if err != nil {
		if m != nil {
			m.HTTPRequestsTotal.WithLabelValues("error").Inc()
			m.HTTPRequestDuration.Observe(duration)
			m.HTTPRequestSize.Observe(float64(len(d.RawEmail)))
		}
		return fmt.Errorf("failed to send HTTP request to URL: %w", err)
	}
	defer resp.Body.Close()

	statusBucket := statusCodeBucket(resp.StatusCode)
	if m != nil {
		m.HTTPRequestsTotal.WithLabelValues(statusBucket).Inc()
		m.HTTPRequestDuration.Observe(duration)
		m.HTTPRequestSize.Observe(float64(len(d.RawEmail)))
	}

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusAccepted {
		bodyBytes, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		if m != nil {
			m.HTTPResponseSize.Observe(float64(len(bodyBytes)))
		}
		return NewHTTPStatusError(resp.StatusCode, string(bodyBytes))
	}

	logger.Info(fmt.Sprintf("Successfully sent email to destination URL, status: %d", resp.StatusCode))
	return nil
}

// IsRetryableError determines if an error should trigger a retry.
// Returns false for permanent failures (4xx HTTP codes, context cancellation).
// Returns true for temporary failures (5xx codes, network errors, timeouts).
func IsRetryableError(err error) bool {
	if err == nil {
		return false
	}

	// Circuit breaker being open is a temporary, retryable state.
	if errors.Is(err, ErrCircuitOpen) {
		return true
	}

	// Check if it's an HTTP status error with specific retry logic
	var httpErr *HTTPStatusError
	if errors.As(err, &httpErr) {
		return httpErr.IsRetryable() // 5xx errors are retryable, 4xx are not
	}

	// Context errors indicate intentional cancellation - don't retry
	if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
		return false
	}

	// Check for specific network errors that are generally retryable.
	var netErr net.Error
	if errors.As(err, &netErr) {
		// Timeouts are always retryable
		if netErr.Timeout() {
			return true
		}

		// DNS lookup errors can be temporary
		var dnsErr *net.DNSError
		if errors.As(err, &dnsErr) {
			return true
		}

		// Connection refused is retryable (server may come back up)
		if strings.Contains(err.Error(), "connection refused") {
			return true
		}

		// Connection reset / broken pipe are retryable
		if strings.Contains(err.Error(), "connection reset") || strings.Contains(err.Error(), "broken pipe") {
			return true
		}

		return false
	}

	// Default to non-retryable for unknown errors to avoid infinite retry loops on unexpected issues.
	return false
}
